spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 1000
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost:3306/examenfinal
    username: root
    password: "root"